services:
  db:
    image: postgres:16-alpine
    container_name: photogallery-db
    environment:
      POSTGRES_DB: photogallery
      POSTGRES_USER: photogallery_user
      POSTGRES_PASSWORD: photogallery_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - photogallery_net

  backend:
    image: python:3.12-slim
    container_name: photogallery-backend
    working_dir: /app
    environment:
      DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost,144.126.143.121,nginx"
      CORS_ALLOWED_ORIGINS: "http://144.126.143.121,http://144.126.143.121:3000,http://localhost:3000"

      DB_NAME: "photogallery"
      DB_USER: "photogallery_user"
      DB_PASSWORD: "photogallery_pass"
      DB_HOST: "db"
      DB_PORT: "5432"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - ./backend/staticfiles:/app/staticfiles
    depends_on:
      - db
    command: >
      sh -c "
        pip install --no-cache-dir -r requirements.txt &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn PhotoGallery.wsgi:application --bind 0.0.0.0:8000
      "
    networks:
      - photogallery_net

  frontend:
    image: node:20-alpine
    container_name: photogallery-frontend
    working_dir: /app
    environment:
      NEXT_PUBLIC_API_BASE: "http://144.126.143.121:8080"
      LOCAL_NEXT_PUBLIC_API_BASE: "http://127.0.0.1:8080"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    command: >
      sh -c "
        npm install &&
        npm run build &&
        npm run start -- -p 3000
      "
    networks:
      - photogallery_net

  nginx:
    image: nginx:alpine
    container_name: photogallery-nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend/media:/app/media:ro
      - ./backend/staticfiles:/app/staticfiles:ro
    networks:
      - photogallery_net


volumes:
  postgres_data:
  frontend_node_modules:

networks:
  photogallery_net:
    driver: bridge
