services:
  backend:
    build: ./backend
    container_name: photogallery-backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app
      - backend_media:/app/media
    networks:
      - photogallery_net

  frontend:
    build: ./frontend
    container_name: photogallery-frontend
    ports:
      - "3000:3000"
    environment:
      # browser uses localhost, keep this
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - photogallery_net

volumes:
  backend_media:

networks:
  photogallery_net:
    driver: bridge
