services:
  db:
    image: postgres:16-alpine
    container_name: photogallery-db
    environment:
      POSTGRES_DB: photogallery
      POSTGRES_USER: photogallery_user
      POSTGRES_PASSWORD: photogallery_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - photogallery_net

  backend:
    build: ./backend
    container_name: photogallery-backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost,backend,144.126.143.121"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://144.126.143.121:3000"

      # Postgres settings for Django
      DB_NAME: "photogallery"
      DB_USER: "photogallery_user"
      DB_PASSWORD: "photogallery_pass"
      DB_HOST: "db"
      DB_PORT: "5432"
    volumes:
      - ./backend:/app
      - backend_media:/app/media
    depends_on:
      - db
    networks:
      - photogallery_net

  frontend:
    build: ./frontend
    container_name: photogallery-frontend
    ports:
      - "3000:3000"
    environment:
      # Browser needs localhost
      NEXT_PUBLIC_API_BASE: "http://144.126.143.121:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - photogallery_net

volumes:
  postgres_data:
  backend_media:

networks:
  photogallery_net:
    driver: bridge
